// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRJ.DataAccess.Context;

#nullable disable

namespace PRJ.DataAccess.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20230627142547_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PRJ.DataAccess.Entities.CARRIER", b =>
                {
                    b.Property<int>("carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("carrier_id"), 1L, 1);

                    b.Property<string>("carrier_mode")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("carrier_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("carrier_id");

                    b.ToTable("CARRIERS");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPMENT", b =>
                {
                    b.Property<int>("shipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipment_id"), 1L, 1);

                    b.Property<int>("carrier_id")
                        .HasColumnType("int");

                    b.Property<string>("shipment_description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("shipment_rate_id")
                        .HasColumnType("int");

                    b.Property<decimal>("shipment_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("shipper_id")
                        .HasColumnType("int");

                    b.HasKey("shipment_id");

                    b.HasIndex("carrier_id");

                    b.HasIndex("shipment_rate_id");

                    b.HasIndex("shipper_id");

                    b.ToTable("SHIPMENTS");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPMENT_RATE", b =>
                {
                    b.Property<int>("shipment_rate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipment_rate_id"), 1L, 1);

                    b.Property<string>("shipment_rate_class")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("shipment_rate_description")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("shipment_rate_id");

                    b.ToTable("SHIPMENT_RATES");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPPER", b =>
                {
                    b.Property<int>("shipper_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipper_id"), 1L, 1);

                    b.Property<string>("shipper_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("shipper_id");

                    b.ToTable("SHIPPERS");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPMENT", b =>
                {
                    b.HasOne("PRJ.DataAccess.Entities.CARRIER", "CARRIER")
                        .WithMany("SHIPMENTS")
                        .HasForeignKey("carrier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRJ.DataAccess.Entities.SHIPMENT_RATE", "SHIPMENT_RATE")
                        .WithMany("SHIPMENTS")
                        .HasForeignKey("shipment_rate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRJ.DataAccess.Entities.SHIPPER", "SHIPPER")
                        .WithMany("SHIPMENTS")
                        .HasForeignKey("shipper_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CARRIER");

                    b.Navigation("SHIPMENT_RATE");

                    b.Navigation("SHIPPER");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.CARRIER", b =>
                {
                    b.Navigation("SHIPMENTS");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPMENT_RATE", b =>
                {
                    b.Navigation("SHIPMENTS");
                });

            modelBuilder.Entity("PRJ.DataAccess.Entities.SHIPPER", b =>
                {
                    b.Navigation("SHIPMENTS");
                });
#pragma warning restore 612, 618
        }
    }
}
